#!/bin/bash
set -e

pip install --no-cache-dir -r ./dev/requirements.txt --upgrade

python ./dev/manage.py migrate
python ./dev/manage.py collectstatic --noinput

exec python ./dev/manage.py runserver 0.0.0.0:8000
#exec service supervisor start