nginx:
  image: nginx:1.9.5
  ports:
    - "8102:8102"
  volumes:
    - ./app:/var/www/html/dev/app
    - ./docker/nginx/sites-enabled/app_dev.conf:/etc/nginx/conf.d/default.conf
  links:
    - web
db:
  image: mysql
  environment:
    TERM: "dumb"
    MYSQL_ROOT_PASSWORD: 1234
phpmemcachedadmin:
  image: jacksoncage/phpmemcachedadmin
  ports:
    - "8103:80"
    - "8104:443"
  links:
    - memcached
memcached:
  image: memcached
web:
  image: rtancman/docker-django
  volumes:
    - ./app:/var/www/html/dev/app
    - ./supervisor:/var/www/html/dev/supervisor
    - ./supervisor/django.ini:/etc/supervisord.d/django.ini
    - ./docker-entrypoint:/usr/local/bin/eventex-entrypoint
  ports:
    - "8000:8000"
  env_file:
    - ./.env
  links:
    - memcached
    - db
  #  command: /usr/local/bin/gunicorn toligado.wsgi:application -w 2 -b :8000