nginx:
  image: nginx:1.9.5
  ports:
    - "80:80"
  volumes:
    - ./app/static:/var/www/html/site/static
    - ./docker/nginx/sites-enabled/app.conf:/etc/nginx/conf.d/default.conf
  links:
    - web
  extra_hosts:
    - "web.dev:127.0.0.1"
memcached:
  image: memcached
web:
  image: rtancman/django:2.7
  volumes:
    - ./app:/var/www/html/dev/app
    - ./logs:/var/www/html/site/logs
    - ./uwsgi:/var/www/html/site/uwsgi
    - ./supervisor/django.conf:/etc/supervisor/conf.d/django.conf
    - ./docker-entrypoint:/usr/local/bin/docker-entrypoint
    # - ./requirements.txt:/var/www/html/site/requirements.txt
    # - ./manage.py:/var/www/html/site/manage.py
  ports:
    - "8000:8000"
  links:
    - memcached